name: Run Tests

on:
  push:
    branches: [ "master" ] # Modifier "main" par "master"
  pull_request:
    branches: [ "master" ] # Modifier "main" par "master"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1' # Gardez votre version de PHP
        extensions: json # Gardez vos extensions

    - name: Install Composer dependencies
      run: composer install --no-interaction --prefer-dist --optimize-autoloader

    - name: Run PHPUnit tests
      run: vendor/bin/phpunit tests