name: Run Tests and Lint Code

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: json

    - name: Install Composer dependencies
      run: composer install --no-interaction --prefer-dist

    - name: Make PHP Code Sniffer executable
      run: chmod +x vendor/bin/phpcs

    - name: Run PHP Code Sniffer
      run: vendor/bin/phpcs --standard=PSR12 src/  # Remplacer 'src/' par le répertoire ou fichier à analyser

    - name: Run PHPUnit tests
      run: vendor/bin/phpunit tests
