name: Run Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1' # Remplacez par la version de PHP de votre projet
        extensions: json # Ajoutez d'autres extensions PHP nécessaires à votre projet et vos tests

    - name: Install Composer dependencies
      run: composer install --no-interaction --prefer-dist --optimize-autoloader

    - name: Run PHPUnit tests
      run: vendor/bin/phpunit tests
      #Hugo le gros gay 