name: Run Tests and Code Style Checks

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: json

    - name: Install Composer dependencies
      run: composer install --no-interaction --prefer-dist --optimize-autoloader

    - name: Generate Composer Autoloader
      run: composer dump-autoload -o

    - name: Make PHPUnit executable
      run: chmod +x vendor/bin/phpunit

    - name: Make PHPCBF executable
      run: chmod +x vendor/bin/phpcbf

    - name: Make PHPCS executable
      run: chmod +x vendor/bin/phpcs

    - name: Fix PHP Code Style Issues
      run: ./vendor/bin/phpcbf --standard=PSR12 src/ tests/ || true

    - name: Run PHP Code Style Checks
      run: ./vendor/bin/phpcs --standard=PSR12 src/ tests/