name: Run Tests

on:
  push:
    branches: [ "master" ] # Modifier "main" par "master"
  pull_request:
    branches: [ "master" ] # Modifier "main" par "master"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    

    - name: Install Composer dependencies
      run: composer install --no-interaction --prefer-dist --optimize-autoloader

    - name: Run PHPUnit tests
      run: vendor/bin/phpunit tests
      
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
          php-version: '8.3' # Ou une version supérieure (e.g., '8.4')
          extensions: json # Gardez vos extensions